#!/bin/sh
# Entrypoint for the sdeploy container.
# Ensures site files generated by deploy runs are created with
# group/world-readable permissions (umask 022 -> 0644 files, 0755 dirs)
# so the Caddy reverse proxy (running as www-data, UID/GID 82) can serve
# them from a shared volume.
set -e

umask 022

exec /usr/local/bin/sdeploy "$@"
